namespace NasLandingPage.Common.Enums;

public enum TableColumn
{
  Name,
  RepoType,
  RepoIsPublic,
  SonarQubeBadges,
  HasReadme,
  HasGitAttributes,
  HasPrTemplate,
  HasEditorConfig,
  HasBuildScripts,
  VersionBuildScripts,
  DirSrc,
  DirTest,
  DirDocs,
  DirDotGithub,
  Languages,
  License,
  Description,
  RepoId,
  RepoDefaultBranch,
  RepoLastUpdate,
  UrlRepo,
  UrlCiCd,
  UrlSonarQube,
  CountRepoForks,
  CountOpenIssues,
  CountBuildScripts,
  CountTestScripts,
  CountWorkFlows,
  RepoSize,
  LastUpdated
}
